Repository DOSOPT-CDS-WEB-TEAM2/CLIENT, pull requests merged in 2023-12, with the labels that each got.

#34 [FEAT] Main페이지 api 연결
  google-finance/src/assets/data/PORTFOLIO_DUMMY.js
  google-finance/src/components/Api/FetchData.js
  google-finance/src/components/Common/NewsArticle.jsx
  google-finance/src/components/Main/EachPortfolio.jsx
  google-finance/src/components/Main/MyPorfolio.jsx
  google-finance/src/pages/Main.jsx
Labels: ✏️Feat

#35 [DESIGN] Nav 바 애니메이션 및 hover 구현
  google-finance/.env
  google-finance/src/assets/icon/ic_menu_search_blue.svg
  google-finance/src/assets/index.jsx
  google-finance/src/components/Api/FetchData.js
  google-finance/src/components/MarketStatus/MarketUSA/MarketTotal.jsx
  google-finance/src/components/Nav/ActiveStock/ActiveStock.jsx
  google-finance/src/components/Nav/ActiveStock/ActiveStockContainer.jsx
  google-finance/src/components/Nav/ActiveStock/StockList.jsx
  google-finance/src/components/Nav/NavBarContent.jsx
  google-finance/src/components/Nav/NavCategory.jsx
  google-finance/src/styles/GlobalStyle.js
Labels: 💅design

#42 [FIX] COMMON 헤더 및 네비 바 홈 이동
  google-finance/src/components/Common/Header.jsx
  google-finance/src/components/Nav/NavBarContent.jsx
Labels: 🛠Fix

#43 [FEAT] Main페이지 api 최종 연결 및 컴포넌트 순서 수정
  google-finance/package.json
  google-finance/src/components/Common/buttons.jsx
  google-finance/src/components/Main/EachPortfolio.jsx
  google-finance/src/components/Main/MyPorfolio.jsx
  google-finance/src/pages/Main.jsx
  google-finance/yarn.lock
  package.json
  yarn.lock
Labels: ✏️Feat

#45 [COMMON] : 모바일 뷰 고정
  google-finance/src/App.jsx
  google-finance/src/styles/GlobalStyle.js
Labels: 💅design
